language: python
python: 2.7
env:
  - TOX_ENV=py27-unit
  - TOX_ENV=py34-unit
  - TOX_ENV=pypy-unit
  - TOX_ENV=flake8
  - TOX_ENV=py27-wheel
  - TOX_ENV=docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
